---
title: "README"
author: "OrKay"
date: "12/21/2014"
output:
  html_document:
    keep_md: yes
---

### Shiny Application Course Project for CoursEra's Developing Data Products course.

This repo contains the code and related documents for the Peer Assessment which is part of the Coursera's Developing Data Products assignment to build Shiny App.

**This Shiny App assignment basically provides list of states in the drop down, 
allowing user to select a state and click submit button to get the facts 
related to the selected state.** Once user clicks the submit button, the data 
from the **state.x77** dataset (that comes with R which contains Facts of US states) 
will be filtered and displayed in the UI.

It is a very simple assignment, fullfilling following requirements to complete it.

1. It uses selectInput widget to let the user input/select a state.
2. The sever.R code utilizes the selected state to filter dataset.
3. The server returns the filtered dataset and ui.R contains the code to display the results.
4. The work includes the documentation (this README file) describing the application.


ShinyApps.io seem to be overwhelmed by the group of online learners.
As a result, the shiny apps cannot be accessed online from time to time. 
Hence, I uploaded all the files necessary to run the app independently of 
ShinyApps.io. The necessary files are:

- ui.R
- server.R
